### ISSUE TITLE
A bug in MonteCarlo.go

### ISSUE THREAD

**Issue by ghooo** [putterson/uxobot#1]
In line 230:
`score = boardPartialScore(subscores, &simBoard, p_move)`

and line 245
`score = boardPartialScore(subscores, &simBoard, move)`

both can be fixed by replacing move to &nomove so the whole board will be reevaluated again. To reproduce the problem disable the randomization factor in here:
`rnd_move_index := rand.Intn(slen)`
make it for example:
`rnd_move_index := 0`

run the code once with my fix, and another without you will be getting different results (print some info regarding the wins/visits of each child of rootnode).

I believe applying my fix is not the best way to go as it will slow down the code A LOT.

**Comment by putterson** [comment]
The issue was that inside the for loop over the child moves, oldscores was not being copied to subscores. Subscores was a pointer to oldscores and so oldscores was modified during the loop, which it shouldn't have been.

Thank you for catching this issue.

Unfortunately the extra array copying caused a small performance regression regardless; from around 30000 playouts per second to around 27000 pps on my machine.

**Comment by ghooo** [comment]
On a related note, you should join this competition http://theaigames.com/competitions/ultimate-tic-tac-toe
